shutdown_costmaps: false
recovery_behavior_enabled: true
clearing_rotation_allowed: true

controller_frequency: 3.0 #5
controller_patience: 3.0  #3


planner_frequency: 1.0
planner_patience: 5.0 #5

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "teb_local_planner/TebLocalPlannerROS" 

base_global_planner: "global_planner/GlobalPlanner" #alternatives: carrot_planner/CarrotPlanner, navfn/NavfnROS

