TebLocalPlannerROS:

  odom_topic: odom
  map_frame: /map

  # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5

  # Robot

  max_vel_x: 0.5  
  max_vel_x_backwards: 0.2  
  max_vel_y: 0.0  
  max_vel_theta: 1.0 
  acc_lim_x: 0.3  
  acc_lim_theta: 0.3  
  acc_lim_y: 0.0  

  # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

  # Footprint model 
  
  footprint_model:
    type: "polygon"
    vertices: [[-0.3, -0.28], [-0.3, 0.28], [0.3, 0.28], [0.3, -0.28]]  # robot's dimensions

  # Obstace avoidance
  min_obstacle_dist: 0.02   
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5